name: CI Pipeline - Build, Scan & Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      

      - name: run Docker Compose command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/
            docker compose up -d
            